// DO NOT EDIT — regenerate via: npm run generate:models
// Source: config/models.toml
//
// This file is committed so the build does not require @iarna/toml at runtime.

export interface SolvelaModel {
  /** Namespaced model ID: "solvela/<gateway-model-id>" */
  id: string;
  /** Display name shown in OpenClaw model picker */
  name: string;
  /** Upstream provider (openai | anthropic | google | deepseek | xai) */
  provider: string;
  contextWindow: number;
  maxTokens: number;
  /** Provider cost per million input tokens (before 5% Solvela fee) */
  inputCostPerMillion: number;
  /** Provider cost per million output tokens (before 5% Solvela fee) */
  outputCostPerMillion: number;
  supportsStreaming: boolean;
  supportsTools?: boolean;
  supportsVision?: boolean;
  supportsStructuredOutput?: boolean;
  reasoning?: boolean;
}

/**
 * All Solvela models generated from config/models.toml.
 * Routing profiles (solvela/auto, solvela/eco, etc.) are added separately
 * by registry.ts and are NOT included here.
 */
export const SOLVELA_MODELS: SolvelaModel[] = [
  {
    "id": "solvela/gpt-5.2",
    "name": "GPT-5.2",
    "provider": "openai",
    "contextWindow": 400000,
    "maxTokens": 32768,
    "inputCostPerMillion": 1.75,
    "outputCostPerMillion": 14,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/gpt-4o",
    "name": "GPT-4o",
    "provider": "openai",
    "contextWindow": 128000,
    "maxTokens": 32768,
    "inputCostPerMillion": 2.5,
    "outputCostPerMillion": 10,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/gpt-4o-mini",
    "name": "GPT-4o Mini",
    "provider": "openai",
    "contextWindow": 128000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.15,
    "outputCostPerMillion": 0.6,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/o3",
    "name": "o3",
    "provider": "openai",
    "contextWindow": 200000,
    "maxTokens": 32768,
    "inputCostPerMillion": 2,
    "outputCostPerMillion": 8,
    "supportsStreaming": true,
    "supportsTools": false,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/gpt-oss-120b",
    "name": "GPT-OSS 120B",
    "provider": "openai",
    "contextWindow": 128000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": false,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/claude-opus-4-8",
    "name": "Claude Opus 4.8",
    "provider": "anthropic",
    "contextWindow": 200000,
    "maxTokens": 32768,
    "inputCostPerMillion": 5,
    "outputCostPerMillion": 25,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/claude-opus-4-7",
    "name": "Claude Opus 4.7",
    "provider": "anthropic",
    "contextWindow": 200000,
    "maxTokens": 32768,
    "inputCostPerMillion": 5,
    "outputCostPerMillion": 25,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/claude-opus-4-6",
    "name": "Claude Opus 4.6",
    "provider": "anthropic",
    "contextWindow": 200000,
    "maxTokens": 32768,
    "inputCostPerMillion": 5,
    "outputCostPerMillion": 25,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/claude-sonnet-4-6",
    "name": "Claude Sonnet 4.6",
    "provider": "anthropic",
    "contextWindow": 200000,
    "maxTokens": 32768,
    "inputCostPerMillion": 3,
    "outputCostPerMillion": 15,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/claude-haiku-4-5-20251001",
    "name": "Claude Haiku 4.5",
    "provider": "anthropic",
    "contextWindow": 200000,
    "maxTokens": 32768,
    "inputCostPerMillion": 1,
    "outputCostPerMillion": 5,
    "supportsStreaming": true,
    "supportsTools": false,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/gemini-3.1-pro",
    "name": "Gemini 3.1 Pro",
    "provider": "google",
    "contextWindow": 1000000,
    "maxTokens": 32768,
    "inputCostPerMillion": 2,
    "outputCostPerMillion": 12,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/gemini-2.5-flash",
    "name": "Gemini 2.5 Flash",
    "provider": "google",
    "contextWindow": 1000000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.3,
    "outputCostPerMillion": 2.5,
    "supportsStreaming": true,
    "supportsTools": false,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/gemini-2.5-flash-lite",
    "name": "Gemini 2.5 Flash Lite",
    "provider": "google",
    "contextWindow": 1000000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.1,
    "outputCostPerMillion": 0.4,
    "supportsStreaming": true,
    "supportsTools": false,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/gemini-3.1-flash-lite",
    "name": "Gemini 3.1 Flash-Lite (Free)",
    "provider": "google",
    "contextWindow": 1000000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/deepseek-chat",
    "name": "DeepSeek V3.2 Chat",
    "provider": "deepseek",
    "contextWindow": 128000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.28,
    "outputCostPerMillion": 0.42,
    "supportsStreaming": true,
    "supportsTools": false,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/deepseek-reasoner",
    "name": "DeepSeek V3.2 Reasoner",
    "provider": "deepseek",
    "contextWindow": 128000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.28,
    "outputCostPerMillion": 0.42,
    "supportsStreaming": true,
    "supportsTools": false,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/grok-4-fast-reasoning",
    "name": "Grok 4 Fast (Reasoning)",
    "provider": "xai",
    "contextWindow": 2000000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.2,
    "outputCostPerMillion": 0.5,
    "supportsStreaming": true,
    "supportsTools": false,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/grok-code-fast-1",
    "name": "Grok Code Fast",
    "provider": "xai",
    "contextWindow": 256000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.2,
    "outputCostPerMillion": 1.5,
    "supportsStreaming": true,
    "supportsTools": false,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/o3-mini",
    "name": "o3 Mini",
    "provider": "openai",
    "contextWindow": 200000,
    "maxTokens": 100000,
    "inputCostPerMillion": 1.1,
    "outputCostPerMillion": 4.4,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": true,
    "reasoning": true
  },
  {
    "id": "solvela/o4-mini",
    "name": "o4 Mini",
    "provider": "openai",
    "contextWindow": 200000,
    "maxTokens": 100000,
    "inputCostPerMillion": 1.1,
    "outputCostPerMillion": 4.4,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": true,
    "reasoning": true
  },
  {
    "id": "solvela/gpt-4.1",
    "name": "GPT-4.1",
    "provider": "openai",
    "contextWindow": 1047576,
    "maxTokens": 32768,
    "inputCostPerMillion": 2,
    "outputCostPerMillion": 8,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": true,
    "reasoning": false
  },
  {
    "id": "solvela/gpt-4.1-mini",
    "name": "GPT-4.1 Mini",
    "provider": "openai",
    "contextWindow": 1047576,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.4,
    "outputCostPerMillion": 1.6,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": true,
    "reasoning": false
  },
  {
    "id": "solvela/gpt-4.1-nano",
    "name": "GPT-4.1 Nano",
    "provider": "openai",
    "contextWindow": 1047576,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.1,
    "outputCostPerMillion": 0.4,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": true,
    "reasoning": false
  },
  {
    "id": "solvela/claude-sonnet-4-5-20250929",
    "name": "Claude Sonnet 4.5",
    "provider": "anthropic",
    "contextWindow": 200000,
    "maxTokens": 16384,
    "inputCostPerMillion": 3,
    "outputCostPerMillion": 15,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/deepseek-coder",
    "name": "DeepSeek Coder V3",
    "provider": "deepseek",
    "contextWindow": 128000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.28,
    "outputCostPerMillion": 0.42,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/grok-3",
    "name": "Grok 3",
    "provider": "xai",
    "contextWindow": 131072,
    "maxTokens": 32768,
    "inputCostPerMillion": 3,
    "outputCostPerMillion": 15,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/grok-3-mini",
    "name": "Grok 3 Mini",
    "provider": "xai",
    "contextWindow": 131072,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.3,
    "outputCostPerMillion": 0.5,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/nvidia/llama-3.1-nemotron-nano-8b-v1",
    "name": "Llama 3.1 Nemotron Nano 8B (Free)",
    "provider": "nvidia",
    "contextWindow": 131072,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/nvidia/llama-3.1-nemotron-ultra-253b-v1",
    "name": "Llama 3.1 Nemotron Ultra 253B (Free)",
    "provider": "nvidia",
    "contextWindow": 131072,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/nvidia/llama-3.3-nemotron-super-49b-v1",
    "name": "Llama 3.3 Nemotron Super 49B (Free)",
    "provider": "nvidia",
    "contextWindow": 131072,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/nvidia/nemotron-3-nano-30b-a3b",
    "name": "Nemotron 3 Nano 30B-A3B (Free)",
    "provider": "nvidia",
    "contextWindow": 131072,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/nvidia/nemotron-3-super-120b-a12b",
    "name": "Nemotron 3 Super 120B-A12B (Free)",
    "provider": "nvidia",
    "contextWindow": 131072,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/nvidia/nemotron-3-ultra-550b-a55b",
    "name": "Nemotron 3 Ultra 550B-A55B (Free)",
    "provider": "nvidia",
    "contextWindow": 131072,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/nvidia/nemotron-mini-4b-instruct",
    "name": "Nemotron Mini 4B Instruct (Free)",
    "provider": "nvidia",
    "contextWindow": 4096,
    "maxTokens": 4096,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/nvidia/llama-3.3-nemotron-super-49b-v1.5",
    "name": "Llama 3.3 Nemotron Super 49B v1.5",
    "provider": "nvidia",
    "contextWindow": 131072,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.1,
    "outputCostPerMillion": 0.4,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/nvidia/nvidia-nemotron-nano-9b-v2",
    "name": "NVIDIA Nemotron Nano 9B v2",
    "provider": "nvidia",
    "contextWindow": 131072,
    "maxTokens": 32768,
    "inputCostPerMillion": 0.04,
    "outputCostPerMillion": 0.16,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/meta/llama-4-maverick-17b-128e-instruct",
    "name": "Llama 4 Maverick 17B-128E (Free)",
    "provider": "nvidia",
    "contextWindow": 1000000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/meta/llama-4-scout-17b-16e-instruct",
    "name": "Llama 4 Scout 17B-16E (Free)",
    "provider": "nvidia",
    "contextWindow": 1000000,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/meta/llama-3.3-70b-instruct",
    "name": "Llama 3.3 70B Instruct (Free)",
    "provider": "nvidia",
    "contextWindow": 131072,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/qwen/qwen3-coder-480b-a35b-instruct",
    "name": "Qwen3 Coder 480B-A35B Instruct (Free)",
    "provider": "nvidia",
    "contextWindow": 262144,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/deepseek-ai/deepseek-r1",
    "name": "DeepSeek-R1 (Free)",
    "provider": "nvidia",
    "contextWindow": 163840,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": true
  },
  {
    "id": "solvela/mistralai/mistral-large-3-675b-instruct-2512",
    "name": "Mistral Large 3 675B Instruct (Free)",
    "provider": "nvidia",
    "contextWindow": 262144,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/minimaxai/minimax-m2.7",
    "name": "MiniMax M2.7 (Free)",
    "provider": "nvidia",
    "contextWindow": 204800,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": false,
    "supportsStructuredOutput": false,
    "reasoning": false
  },
  {
    "id": "solvela/minimaxai/minimax-m3",
    "name": "MiniMax M3 (Free)",
    "provider": "nvidia",
    "contextWindow": 204800,
    "maxTokens": 32768,
    "inputCostPerMillion": 0,
    "outputCostPerMillion": 0,
    "supportsStreaming": true,
    "supportsTools": true,
    "supportsVision": true,
    "supportsStructuredOutput": false,
    "reasoning": false
  }
];

export const MODEL_COUNT = 44;
