[book]
title = "RustyClawRouter Documentation"
authors = ["Kenneth Dixon"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "../../target/book"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/kennethdixon/RustyClawRouter"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.admonish]
command = "mdbook-admonish"
