[toolchain]
anchor_version = "0.31.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
rustyclawrouter_escrow = "GTs7ik3NbW3xwSXq33jyVRGgmshNEyW1h9rxDNATiFLy"

[programs.devnet]
rustyclawrouter_escrow = "GTs7ik3NbW3xwSXq33jyVRGgmshNEyW1h9rxDNATiFLy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --lib"
